version: '3'

services:
  # click:
  #   build:
  #     context: .
  #     dockerfile: .devcontainer/Dockerfile
  #   tty: true
  #   volumes:
  #     - ./click2:/code
  #   ports:
  #     - '8000:8000'
  # argparse:
  #   build:
  #     context: .
  #     dockerfile: .devcontainer/Dockerfile
  #   tty: true
  #   volumes:
  #     - ./argparse:/code
  #   ports:
  # - '8000:8000'
  # fire:
  #   build:
  #     context: .
  #     dockerfile: .devcontainer/Dockerfile
  #   tty: true
  #   volumes:
  #     - ./fire:/code
  #   ports:
  #     - '8000:8000'
  node:
    build:
      context: ./vorpal
      dockerfile: Dockerfile.node
    tty: true
    stdin_open: true
    volumes:
      - ./vorpal:/code
    ports:
      - '8000:8000'
