version: '3'

services:
  click:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    tty: true
    volumes:
      - ./click2:/code
    ports:
      - '8000:8000'
  argparse:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    tty: true
    volumes:
      - ./argparse:/code
    ports:
      - '8000:8000'
  fire:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    tty: true
    volumes:
      - ./fire:/code
    ports:
      - '8000:8000'
  node:
    build:
      context: ./vorpal
      dockerfile: Dockerfile.node
    tty: true
    stdin_open: true
    volumes:
      - ./vorpal:/code
    ports:
      - '8000:8000'
  julia:
    image: jupyter/datascience-notebook:latest
    user: root
    ports:
      - '8101:8888'
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./julia:/home/jovyan/code
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.notebook_dir='/home/jovyan/work'

  python:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    tty: true
    volumes:
      - ./misc:/code
    ports:
      - '8000:8000'
